// CODEBASE.md is the description of a project written FOR agents, and it was
// generated once and never again: this repository's own sat at its first-run
// snapshot for eleven days and twenty commits, claiming 325 source files and
// 63,023 LOC where there were 396 and 78,141 — eighteen percent short.
//
// The header line promised "delete this line to stop auto-regen", and the guard
// exited before reading the file at all, so regeneration never happened once. A
// promise the code did not keep.
//
// Staleness here is worse than in human documentation. A person opening a stale
// ARCHITECTURE.md notices it says thirty-four agents; an agent reading a stale
// CODEBASE.md notices nothing and builds on the wrong map.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const SCRIPT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../scripts/first-run-codebase.mjs');

function project({ codebase = null, files = 3 } = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gcto-cb-'));
  fs.mkdirSync(path.join(dir, '.great_cto'), { recursive: true });
  fs.writeFileSync(path.join(dir, '.great_cto', 'PROJECT.md'), 'primary: devtools\n');
  fs.mkdirSync(path.join(dir, 'src'), { recursive: true });
  for (let i = 0; i < files; i++) fs.writeFileSync(path.join(dir, 'src', `f${i}.mjs`), 'export const x = 1;\n'.repeat(5));
  if (codebase !== null) fs.writeFileSync(path.join(dir, '.great_cto', 'CODEBASE.md'), codebase);
  return dir;
}
const run = (dir) => execFileSync('node', [SCRIPT], { cwd: dir, stdio: 'ignore' });
const read = (dir) => { const p = path.join(dir, '.great_cto', 'CODEBASE.md'); return fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null; };
const clean = (d) => { try { fs.rmSync(d, { recursive: true, force: true }); } catch {} };

test('a missing map is generated', () => {
  const dir = project();
  try { run(dir); assert.match(read(dir), /# CODEBASE/); } finally { clean(dir); }
});

test('a map whose facts have moved is regenerated', () => {
  // The defect: the guard exited on existence, so this never happened.
  const dir = project({ codebase: '> Generated by great_cto first-run scan on 2020-01-01 — a starter map.\n\n# CODEBASE\n\n**Size:** 1 source files · ~1 LOC\n' });
  try {
    run(dir);
    const after = read(dir);
    assert.ok(!/1 source files/.test(after), 'the stale count must be gone');
    assert.match(after, /source files/);
  } finally { clean(dir); }
});

test('a map whose facts have not moved is left byte-identical', () => {
  // Rewriting on every session start makes the file's own timestamp meaningless
  // and looks like a project that changes constantly.
  const dir = project();
  try {
    run(dir);
    const first = read(dir);
    const mtime = fs.statSync(path.join(dir, '.great_cto', 'CODEBASE.md')).mtimeMs;
    run(dir);
    assert.equal(read(dir), first);
    assert.equal(fs.statSync(path.join(dir, '.great_cto', 'CODEBASE.md')).mtimeMs, mtime, 'not even touched');
  } finally { clean(dir); }
});

test('a hand-owned map is never touched', () => {
  // Removing the marker line is how an author claims the file, and the marker
  // itself says so.
  const own = '# CODEBASE\n\nWritten by a person. No marker line.\n';
  const dir = project({ codebase: own });
  try { run(dir); assert.equal(read(dir), own); } finally { clean(dir); }
});

test('a project with no PROJECT.md is not a great_cto project and is skipped', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gcto-plain-'));
  try { run(dir); assert.equal(read(dir), null); } finally { clean(dir); }
});

test('the opt-out still stops it dead', () => {
  const dir = project();
  try {
    execFileSync('node', [SCRIPT], { cwd: dir, stdio: 'ignore', env: { ...process.env, GREAT_CTO_NO_FIRST_RUN: '1' } });
    assert.equal(read(dir), null);
  } finally { clean(dir); }
});
