// Tests for scripts/generate-summary.mjs and scripts/hooks/summary-enforce.mjs
//
// Run with:  node --test tests/hooks/summary-enforce.test.mjs

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync, existsSync, statSync, utimesSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const GENERATE = resolve(__dirname, '../../scripts/generate-summary.mjs');
const HOOK = resolve(__dirname, '../../scripts/hooks/summary-enforce.mjs');

function tempArtifactDir() {
  const root = mkdtempSync(join(tmpdir(), 'gcto-summary-'));
  for (const sub of ['docs/architecture', 'docs/plans', 'docs/qa', 'docs/security']) {
    spawnSync('mkdir', ['-p', join(root, sub)]);
  }
  return root;
}

function writeArtifact(root, relPath, content) {
  const full = join(root, relPath);
  writeFileSync(full, content, 'utf-8');
  return full;
}

function runGenerate(args, opts = {}) {
  const r = spawnSync('node', [GENERATE, ...args], {
    encoding: 'utf-8',
    cwd: opts.cwd ?? process.cwd(),
    // Force heuristic fallback by clearing API keys (don't actually call out from tests)
    env: { ...process.env, ANTHROPIC_API_KEY: '', OPENROUTER_API_KEY: '' },
  });
  return { exit: r.status, stdout: r.stdout, stderr: r.stderr };
}

function runHook(payload, cwd) {
  const r = spawnSync('node', [HOOK], {
    input: JSON.stringify(payload),
    encoding: 'utf-8',
    cwd,
    env: { ...process.env, ANTHROPIC_API_KEY: '', OPENROUTER_API_KEY: '' },
  });
  return { exit: r.status, stdout: r.stdout, stderr: r.stderr };
}

test('classifies artifact types correctly', async () => {
  // Lazy-import for ESM module under test
  const mod = await import('../../scripts/generate-summary.mjs');
  assert.equal(mod.classify('docs/architecture/ARCH-foo.md'), 'architecture');
  assert.equal(mod.classify('docs/architecture/ADR-013.md'), 'architecture');
  assert.equal(mod.classify('docs/architecture/PHASE-x.md'), 'architecture');
  assert.equal(mod.classify('docs/plans/PLAN-foo.md'), 'plan');
  assert.equal(mod.classify('docs/qa/QA-foo.md'), 'qa');
  assert.equal(mod.classify('docs/security/SEC-foo.md'), 'security');
  assert.equal(mod.classify('docs/security/TM-foo.md'), 'security');
  assert.equal(mod.classify('docs/release/RELEASE-1.md'), 'release');
  assert.equal(mod.classify('docs/performance/PERF-foo.md'), 'performance');
  assert.equal(mod.classify('docs/other/README.md'), 'generic');
});

test('heuristic summary extracts H1 and bullets', async () => {
  const mod = await import('../../scripts/generate-summary.mjs');
  const content = `# My Doc

Some intro.

## Decisions

- Use Postgres for primary store
- Use Redis for cache
- Reject GraphQL for now
`;
  const summary = mod.heuristicSummary(content, 'architecture');
  assert.match(summary, /# My Doc · summary/);
  assert.match(summary, /Use Postgres/);
  assert.match(summary, /Full doc:/);
});

test('generator writes .summary.md for ARCH artifact (heuristic mode)', () => {
  const root = tempArtifactDir();
  const arch = writeArtifact(root, 'docs/architecture/ARCH-test-feature.md',
    '# ARCH-test\n\n## Decisions\n\n- Pick X\n- Pick Y\n');

  const r = runGenerate([arch], { cwd: root });
  assert.equal(r.exit, 0, `stderr: ${r.stderr}`);

  const summary = arch.replace(/\.md$/, '.summary.md');
  assert.ok(existsSync(summary), 'summary file should exist');

  const content = readFileSync(summary, 'utf-8');
  assert.match(content, /auto-generated by scripts\/generate-summary\.mjs/);
  assert.match(content, /mode=heuristic/);
  assert.match(content, /# ARCH-test · summary/);
});

test('generator is idempotent — skips when summary newer than source', () => {
  const root = tempArtifactDir();
  const arch = writeArtifact(root, 'docs/plans/PLAN-x.md', '# PLAN-x\n\n- a\n- b\n');

  runGenerate([arch], { cwd: root });
  const summary = arch.replace(/\.md$/, '.summary.md');
  const firstMtime = statSync(summary).mtimeMs;

  // Wait a bit, run again without --force, summary should be unchanged
  const r2 = runGenerate([arch], { cwd: root });
  assert.equal(r2.exit, 0);
  const secondMtime = statSync(summary).mtimeMs;
  assert.equal(firstMtime, secondMtime, 'should not regenerate fresh summary');
});

test('generator regenerates when source is newer (force semantic)', async () => {
  const root = tempArtifactDir();
  const arch = writeArtifact(root, 'docs/plans/PLAN-y.md', '# v1\n\n- old\n');

  runGenerate([arch], { cwd: root });
  const summary = arch.replace(/\.md$/, '.summary.md');
  const firstContent = readFileSync(summary, 'utf-8');

  // Make source newer than summary by touching its mtime forward
  const future = new Date(Date.now() + 10_000);
  utimesSync(arch, future, future);
  writeFileSync(arch, '# v2\n\n- new\n');
  utimesSync(arch, future, future);

  runGenerate([arch], { cwd: root });
  const secondContent = readFileSync(summary, 'utf-8');
  assert.notEqual(firstContent, secondContent, 'summary should regenerate when source changes');
});

test('--check exits 2 when stale summaries exist', () => {
  const root = tempArtifactDir();
  writeArtifact(root, 'docs/architecture/ARCH-stale.md', '# stale\n\n- foo\n');
  // No summary written yet — should be stale

  const r = runGenerate(['--check'], { cwd: root });
  assert.equal(r.exit, 2, `stderr: ${r.stderr}`);
});

test('--check exits 0 when all summaries fresh', () => {
  const root = tempArtifactDir();
  const arch = writeArtifact(root, 'docs/architecture/ARCH-fresh.md', '# fresh\n');
  runGenerate([arch], { cwd: root });

  const r = runGenerate(['--check'], { cwd: root });
  assert.equal(r.exit, 0, `stderr: ${r.stderr}`);
});

test('--all generates summaries for all artifacts in tree', () => {
  const root = tempArtifactDir();
  writeArtifact(root, 'docs/architecture/ARCH-1.md', '# a\n');
  writeArtifact(root, 'docs/plans/PLAN-1.md', '# p\n');
  writeArtifact(root, 'docs/qa/QA-1.md', '# q\n');
  writeArtifact(root, 'docs/architecture/README.md', '# readme\n'); // shouldn't match

  const r = runGenerate(['--all'], { cwd: root });
  assert.equal(r.exit, 0);
  assert.ok(existsSync(join(root, 'docs/architecture/ARCH-1.summary.md')));
  assert.ok(existsSync(join(root, 'docs/plans/PLAN-1.summary.md')));
  assert.ok(existsSync(join(root, 'docs/qa/QA-1.summary.md')));
  assert.ok(!existsSync(join(root, 'docs/architecture/README.summary.md')),
    'non-prefixed files should be ignored');
});

test('does NOT summarize files outside artifact dirs', () => {
  const root = tempArtifactDir();
  spawnSync('mkdir', ['-p', join(root, 'docs/other')]);
  writeArtifact(root, 'docs/other/ARCH-not-real.md', '# nope\n');

  const r = runGenerate(['--all'], { cwd: root });
  assert.equal(r.exit, 0);
  assert.ok(!existsSync(join(root, 'docs/other/ARCH-not-real.summary.md')));
});

test('does NOT summarize a .summary.md file', () => {
  const root = tempArtifactDir();
  const summaryAsSource = writeArtifact(root, 'docs/architecture/ARCH-x.summary.md', '# fake\n');

  const r = runGenerate([summaryAsSource], { cwd: root });
  // Behavior: classify still works but the path itself ends in .summary.md and
  // generateOne will not produce a .summary.summary.md if the input is treated normally.
  // Verify no double-summary file is created:
  assert.ok(!existsSync(summaryAsSource.replace(/\.summary\.md$/, '.summary.summary.md')));
});

test('hook reads stdin and logs trigger for matching artifact', () => {
  const root = tempArtifactDir();
  const arch = writeArtifact(root, 'docs/architecture/ARCH-hook-test.md', '# x\n');

  const r = runHook({ tool_input: { file_path: arch } }, root);
  assert.equal(r.exit, 0);

  // Hook logs to .great_cto/summary.log
  const logPath = join(root, '.great_cto', 'summary.log');
  assert.ok(existsSync(logPath), 'hook should create summary.log');
  const log = readFileSync(logPath, 'utf-8');
  assert.match(log, /TRIGGER/);
});

test('hook ignores non-artifact files (no log entry)', () => {
  const root = tempArtifactDir();
  // Use a tmp file outside artifact dirs
  const tmp = join(root, 'src/random.md');
  spawnSync('mkdir', ['-p', join(root, 'src')]);
  writeFileSync(tmp, '# random\n');

  const r = runHook({ tool_input: { file_path: tmp } }, root);
  assert.equal(r.exit, 0);

  // Log should NOT have a TRIGGER line for this file
  const logPath = join(root, '.great_cto', 'summary.log');
  if (existsSync(logPath)) {
    const log = readFileSync(logPath, 'utf-8');
    assert.ok(!log.includes(tmp), 'hook should not log non-artifact files');
  }
});

test('hook respects GREAT_CTO_DISABLE_SUMMARY=1', () => {
  const root = tempArtifactDir();
  const arch = writeArtifact(root, 'docs/architecture/ARCH-disabled.md', '# x\n');

  const r = spawnSync('node', [HOOK], {
    input: JSON.stringify({ tool_input: { file_path: arch } }),
    encoding: 'utf-8',
    cwd: root,
    env: { ...process.env, GREAT_CTO_DISABLE_SUMMARY: '1' },
  });
  assert.equal(r.status, 0);
  // No log file created (early return before mkdir)
  const logPath = join(root, '.great_cto', 'summary.log');
  if (existsSync(logPath)) {
    const log = readFileSync(logPath, 'utf-8');
    assert.ok(!log.includes('ARCH-disabled'));
  }
});
