// Generated by scripts/build-gate-policy.mjs from packages/cli/src/archetypes.ts.
// Do not edit; regenerate, then run --check. No CLI build is needed at runtime.
export const GATES_BY_ARCHETYPE = {
    "web-service": ["plan", "qa", "ship"],
    "mobile-app": ["plan", "qa", "ship"],
    "ai-system": ["plan", "cost", "qa", "security", "ship"],
    "agent-product": ["plan", "cost", "qa", "security", "ship"],
    "mlops": ["plan", "cost", "qa", "security", "ship"],
    "data-platform": ["plan", "qa", "ship"],
    "streaming": ["plan", "qa", "ship"],
    "infra": ["plan", "qa", "ship"],
    "library": ["plan", "qa", "ship"],
    "cli-tool": ["plan", "qa", "ship"],
    "commerce": ["plan", "qa", "security", "ship", "compliance"],
    "marketplace": ["plan", "qa", "security", "ship", "compliance"],
    "fintech": ["plan", "qa", "security", "ship", "compliance"],
    "healthcare": ["plan", "qa", "security", "ship", "compliance"],
    "web3": ["plan", "qa", "oracle-review", "security", "ship"],
    "iot-embedded": ["plan", "qa", "security", "ship"],
    "regulated": ["plan", "qa", "security", "ship", "compliance"],
    "devtools": ["plan", "qa", "ship"],
    "browser-extension": ["plan", "qa", "ship"],
    "game": ["plan", "qa", "ship"],
    "cms": ["plan", "qa", "ship"],
    "enterprise-saas": ["plan", "qa", "security", "ship", "compliance"],
    "edtech": ["plan", "qa", "edtech-review", "security", "ship", "compliance"],
    "gov-public": ["plan", "qa", "gov-review", "security", "ship", "compliance"],
    "insurance": ["plan", "qa", "insurance-review", "security", "ship", "compliance"],
    "legal": ["plan", "qa", "upl-review", "security", "ship", "compliance"],
    "defense-govcon": ["plan", "qa", "cmmc-assessment", "security", "ship", "compliance"],
    // Product Builder archetypes (A1–A6) — non-regulated baseline; the single CTO gate
    // emerges at change_tier T1 (effectiveGates → [plan]).
    "vertical-saas": ["plan", "qa", "ship"],
    "booking": ["plan", "qa", "ship"],
    "crm": ["plan", "qa", "ship"],
    "dashboard": ["plan", "qa", "ship"],
    "content-platform": ["plan", "qa", "ship"],
    "marketplace-lite": ["plan", "qa", "ship"],
    "greenfield": ["plan"],
};
/**
 * Returns the subset of gates the pipeline will actually open for a
 * given archetype + project_size. Used by the orchestrator before
 * opening any gate to skip unnecessary human checkpoints on smaller
 * projects (e.g. nano always skips QA).
 */
export function gatesFor(archetype, size) {
    const all = GATES_BY_ARCHETYPE[archetype] ?? [];
    if (size === "nano")
        return all.filter((g) => g === "plan");
    if (size === "small")
        return all.filter((g) => g === "plan" || g === "ship");
    if (size === "medium")
        return all;
    // large + enterprise → ensure compliance is included
    return all.includes("compliance") ? all : [...all, "compliance"];
}
/** Gates that form the non-negotiable floor for a *regulated* archetype. */
const FLOOR_GATES = ["security", "compliance", "ship"];
/**
 * The human gates the pipeline opens for a change, given its archetype, the
 * project size, AND the per-change risk tier. Composes with `gatesFor()`:
 *
 *  - T2 (default): the full size baseline, with `ship` guaranteed even if a
 *    small project_size had stripped it. An irreversible change always gets a
 *    final go/no-go. Nothing is ever removed → fail-safe for an unknown tier.
 *  - T1: only `plan` (you review intent) PLUS the regulated floor. The standalone
 *    qa/security-as-ceremony is dropped because CI + tests cover a reversible change.
 *  - T0: the regulated floor only — for a plain archetype that is the empty set
 *    (CI is the gate); for a regulated one, security+compliance+ship still fire.
 *
 * An archetype is "regulated" iff its baseline contains `security` or `compliance`.
 * That is what keeps the downgrade sound: a fintech repo cannot ship an
 * irreversible change unreviewed even when the change is labelled a fix.
 *
 * NOTE: change-specific T2 triggers (a migration, a new write-connector, a prod
 * deploy) are resolved upstream by the classifier, which escalates such a change
 * to T2 before this function sees it. Here we only map an already-decided tier.
 */
export function effectiveGates(archetype, size, tier = "T2") {
    const base = gatesFor(archetype, size);
    // T2 (and any unrecognized tier) → full baseline, never downgraded, ship forced.
    if (tier !== "T0" && tier !== "T1") {
        return base.includes("ship") ? base : [...base, "ship"];
    }
    // Regulated archetypes carry a floor that survives every downgrade.
    const isRegulated = base.includes("security") || base.includes("compliance");
    const floor = isRegulated ? base.filter((g) => FLOOR_GATES.includes(g)) : [];
    if (tier === "T1") {
        const keep = new Set(floor);
        if (base.includes("plan"))
            keep.add("plan");
        return base.filter((g) => keep.has(g)); // preserve base order
    }
    // T0 — maintenance.
    return floor;
}
