/**
 * The project the documentation screenshots are taken from.
 *
 * Never the operator's own board. That board lists every project with a
 * `.great_cto/PROJECT.md` on the machine — which for this project's author means
 * client work whose names may not appear in a public repository — and prints
 * paths that begin with the operator's home directory and username.
 *
 * One screenshot already in `docs/screenshots/` was taken this way (a synthetic
 * insurance console). This makes it the rule rather than the one that happened to
 * be careful.
 *
 * Everything below is invented: ACME is the canonical fictional company, and no
 * name, path, handle or figure here comes from a real project.
 *
 * @see scripts/capture-screenshots.mjs
 */

import fs from 'node:fs';
import path from 'node:path';

/** ISO timestamps relative to a fixed instant, so a capture is reproducible. */
const T0 = Date.parse('2026-08-20T09:00:00Z');
const at = (hoursAgo) => new Date(T0 - hoursAgo * 3600_000).toISOString();

const PROJECT_MD = `# acme-storefront

Auto-generated by \`great-cto init\`.
Edit freely — this file is yours. Re-run \`npx great-cto init\` won't overwrite it.

## Project

primary: web-service
secondary: e-commerce
archetype: commerce
project_size: medium
stack: TypeScript, Next.js, Postgres
languages: typescript
package-manager: npm

## Phase

phase: implementation

## Team

team-size: 4
mode: team
approval-level: gates-only

## Compliance

compliance: pci-dss, soc2-type-2
jurisdiction: us, eu

## Budgets

monthly-budget: $400
per-run-usd: 12
`;

const TASKS_MD = `# acme-storefront — tasks

## Build

| id | title | size | horizon | status | owner |
|----|-------|------|---------|--------|-------|
| acme-1a | Checkout: idempotency key on every payment intent | M | H1 | in_progress | senior-dev |
| acme-2b | Cart totals disagree with the invoice on partial refund | S | H1 | in_progress | senior-dev |
| acme-3c | gate:ship — checkout hardening | XS | H1 | open | CTO |
| acme-4d | Webhook signature verification for the payment provider | M | H1 | done | senior-dev |
| acme-5e | Storefront: product grid loses focus ring on keyboard nav | S | H2 | open | senior-dev |
| acme-6f | Postgres connection pool exhausts under burst traffic | L | H1 | blocked | devops |
| acme-7g | PCI scope: confirm SAQ-A, not SAQ-D | S | H1 | done | security-officer |
| acme-8h | Seed catalogue import from the incumbent CSV export | M | H2 | open | senior-dev |

## Findings

| id | severity | finding | status |
|----|----------|---------|--------|
| acme-f1 | High | Refund path retries without an idempotency key | open |
| acme-f2 | Medium | Session cookie missing SameSite on the checkout subdomain | done |
`;

const VERDICTS = [
  ['qa-engineer', 'PASS', 'checkout-hardening', 4,
    'Golden path passes: cart → address → pay → receipt. Partial-refund total still disagrees with the invoice; filed acme-2b.'],
  ['security-officer', 'PASS', 'pci-scope', 9,
    'SAQ-A confirmed — card data never reaches our origin. Webhook signatures verified on every inbound event.'],
  ['code-reviewer', 'REWORK', 'checkout-hardening', 2,
    'The retry wrapper drops the idempotency key on the second attempt, so a refund can be applied twice.'],
];

const COST_LOG = [
  [at(30), 'architect', 0.42], [at(28), 'pm', 0.31], [at(24), 'senior-dev', 1.86],
  [at(20), 'senior-dev', 2.14], [at(14), 'qa-engineer', 0.94],
  [at(9), 'security-officer', 0.63], [at(4), 'code-reviewer', 0.77],
].map(([ts, agent, usd]) => JSON.stringify({ ts, agent, usd, model: 'claude-opus-5' })).join('\n') + '\n';

/**
 * Write the fixture project into `dir`. Idempotent: the same input every time,
 * so two captures of an unchanged UI differ only in the pixels the UI changed.
 * @returns {string} the project root that was written
 */
export function buildFixture(dir) {
  const gc = path.join(dir, '.great_cto');
  fs.mkdirSync(path.join(gc, 'verdicts'), { recursive: true });
  fs.mkdirSync(path.join(gc, 'logs'), { recursive: true });

  fs.writeFileSync(path.join(gc, 'PROJECT.md'), PROJECT_MD);
  fs.writeFileSync(path.join(gc, 'tasks.md'), TASKS_MD);
  fs.writeFileSync(path.join(gc, 'brain.md'),
    '# Patterns in use\n\n- Every write to the payment provider carries an idempotency key.\n'
    + '- Totals are computed once, server-side, and never recomputed in the client.\n');
  fs.writeFileSync(path.join(gc, 'lessons.md'),
    '# Lessons\n\n- A retry without an idempotency key is not a retry, it is a second charge.\n');
  fs.writeFileSync(path.join(gc, 'cost-history.log'), COST_LOG);

  for (const [agent, verdict, feature, hoursAgo, note] of VERDICTS) {
    fs.writeFileSync(path.join(gc, 'verdicts', `${agent}-${feature}.md`),
      `---\nagent: ${agent}\nverdict: ${verdict}\nfeature: ${feature}\ndate: ${at(hoursAgo)}\n---\n\n${note}\n`);
  }

  fs.writeFileSync(path.join(gc, 'logs', 'session-2026-08-19.md'),
    `# Session — checkout hardening\n\nWhat was done:\n- Idempotency keys on payment intents\n`
    + `- Webhook signature verification\n\nLeft pending:\n- Partial-refund totals (acme-2b)\n`);

  // A real project shape. `great-cto ci` detects the archetype from the code, and
  // an empty directory detects as greenfield — a fixture that fails the product's
  // own check is a fixture that cannot demonstrate it.
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    name: 'acme-storefront', version: '0.4.0', private: true, type: 'module',
    scripts: { dev: 'next dev', build: 'next build', test: 'vitest run' },
    dependencies: { next: '^15.0.0', react: '^19.0.0', 'react-dom': '^19.0.0', stripe: '^17.0.0' },
    devDependencies: { typescript: '^5.6.0', vitest: '^2.0.0' },
  }, null, 2) + '\n');
  fs.mkdirSync(path.join(dir, 'src', 'app'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'src', 'app', 'page.tsx'),
    'export default function Storefront() {\n  return <main>ACME</main>;\n}\n');
  fs.writeFileSync(path.join(dir, 'src', 'checkout.ts'),
    '/** Every payment intent carries an idempotency key. */\n'
    + 'export async function createIntent(cartId: string, key: string) {\n'
    + '  return { cartId, idempotencyKey: key };\n}\n');
  fs.writeFileSync(path.join(dir, 'tsconfig.json'),
    JSON.stringify({ compilerOptions: { strict: true, module: 'esnext', target: 'es2022' } }, null, 2) + '\n');

  // A README so the Docs screen has something of its own to list.
  fs.writeFileSync(path.join(dir, 'README.md'),
    '# acme-storefront\n\nA sample commerce project used to photograph the great_cto board.\n');
  fs.mkdirSync(path.join(dir, 'docs'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'docs', 'ARCHITECTURE.md'),
    '# Architecture\n\nNext.js storefront, Postgres, a payment provider held at arm\'s length.\n'
    + 'See [the checkout decision](decisions/ADR-001-checkout.md).\n');
  fs.mkdirSync(path.join(dir, 'docs', 'decisions'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'docs', 'decisions', 'ADR-001-checkout.md'),
    '# ADR-001 — Checkout stays off our origin\n\n**Status:** Accepted\n\n'
    + 'Card data never reaches our servers, which keeps us in PCI SAQ-A.\n');

  return dir;
}

export const FIXTURE_NAME = 'acme-storefront';
