// great-cto adapt — Claude Code config generator.
//
// Writes CLAUDE.md + AGENTS.md from .great_cto/PROJECT.md context.
//
// Usage:
//   great-cto adapt            Generate CLAUDE.md + AGENTS.md
//   great-cto adapt --dry-run  Show what would be written

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

export type Platform = "claude";

export interface AdaptArgs {
  platform: Platform;
  dryRun: boolean;
  cwd: string;
}

interface ProjectMeta {
  archetype: string;
  compliance: string[];
  owners: string;
  hasGreatCto: boolean;
}

function readProjectMeta(cwd: string): ProjectMeta {
  const projectMd = join(cwd, ".great_cto", "PROJECT.md");
  if (!existsSync(projectMd)) {
    return { archetype: "unknown", compliance: [], owners: "", hasGreatCto: false };
  }
  const text = readFileSync(projectMd, "utf8");
  const archetype = (text.match(/^primary:\s*(\S+)/m)?.[1] ?? "unknown").trim();
  const complianceLine = text.match(/^compliance:\s*(.+)$/m)?.[1] ?? "";
  const compliance = complianceLine
    .split(/[,\s]+/)
    .map(s => s.trim())
    .filter(Boolean);
  const owners = (text.match(/^owners?:\s*(.+)$/m)?.[1] ?? "").trim();
  return { archetype, compliance, owners, hasGreatCto: true };
}

/**
 * AGENTS.md — Claude Code reads this as the cross-tool agent contract.
 */
function getAgentsCore(meta: ProjectMeta): string {
  const compliance = meta.compliance.length > 0
    ? meta.compliance.map(c => `- ${c}`).join("\n")
    : "_(none auto-detected — set in .great_cto/PROJECT.md)_";

  return `# AGENTS.md

> Project agent contract for Claude Code. Generated by \`great-cto adapt\` —
> re-run after editing \`.great_cto/PROJECT.md\`.

## Project context

- **Archetype:** ${meta.archetype}
- **Compliance gates:**
${compliance.split("\n").map(l => "  " + l).join("\n")}
- **Owners:** ${meta.owners || "_(unset)_"}

## How agents should work in this repo

1. **Before touching code** — read \`.great_cto/PROJECT.md\` (archetype +
   constraints) and \`.great_cto/lessons.md\` if present (past mistakes).
2. **Before proposing a fix** — query \`~/.great_cto/decisions.md\` for ADRs
   on related topics. Solved problems should stay solved.
3. **Before merging** — run \`npx great-cto ci\` locally. Same gate as CI.
4. **On failure / incident** — append to \`.great_cto/lessons.md\`. After 3
   occurrences across projects, \`/crystallize\` promotes to global pattern.

## Required gates (do not bypass)

| Gate | When | Owner |
|---|---|---|
| security-officer | Any change touching auth, payments, PII | @security |
| qa-engineer | Any feature merge | @qa |
| performance-engineer | Any change to hot path | @perf |
| db-migration-reviewer | Any \`migrations/\` change | @data |

Override with \`/waiver\` and a written reason. Auto-expires in 14 days.

## Available tools (via MCP)

When this repo is opened in Claude Code, \`great-cto mcp\` exposes:

- \`scan\` — OWASP LLM Top 10 + 24 rules · returns findings
- \`list_rules\` — full rule catalogue
- \`detect_archetype\` — archetype + compliance for any path
- \`estimate_cost\` — LLM vs human time estimate for a task
- \`query_decisions\` — search ADR log

Configure Claude Code to launch:
\`\`\`bash
npx great-cto mcp
\`\`\`

## Style + conventions

- Tests **before** implementation (RED → GREEN → REFACTOR). Coverage 80%+ default.
- Conventional commits: \`feat\` / \`fix\` / \`docs\` / \`refactor\` / \`test\` / \`chore\`.
- One concern per PR. Refactors and behaviour changes are separate PRs.
- No secrets in code. \`great-cto scan\` blocks ~13 patterns by default.

## Out of scope

Do not invent business decisions. If the spec is ambiguous, ask. Do not skip
gates "because it's just a small change" — that's the path to incidents.

---

_Generated by \`great-cto@${getCliVersion()}\` adapt at ${new Date().toISOString().slice(0, 10)}_
`;
}

function getCliVersion(): string {
  try {
    const here = dirname(new URL(import.meta.url).pathname);
    const pkg = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf8"));
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
}

function writeFile(path: string, content: string, dryRun: boolean): boolean {
  if (dryRun) {
    console.log(`would write: ${path} (${content.length} bytes)`);
    return false;
  }
  mkdirSync(dirname(path), { recursive: true });
  const existed = existsSync(path);
  writeFileSync(path, content);
  console.log(`  ${existed ? "✎ updated" : "✓ wrote"}  ${path}`);
  return true;
}

// ── Claude Code adapter ────────────────────────────────────────────────────

function adaptClaude(cwd: string, meta: ProjectMeta, dryRun: boolean): string[] {
  const out: string[] = [];
  const agentsBody = getAgentsCore(meta);
  const claudeBody = `# CLAUDE.md

> Project guidance for Claude Code. The full agent contract lives in
> \`AGENTS.md\` — please read that first. This file adds Claude Code-specific
> overrides only.

## Cross-tool contract

See [AGENTS.md](./AGENTS.md) for the full project context, gates, and
conventions. Generated by \`great-cto adapt\`.

## Claude Code specifics

- The great_cto plugin orchestrates 34 specialist agents — pipeline runs
  through \`/start\`, \`/inbox\`, \`/save\`, etc.
- Memory is layered: \`.great_cto/PROJECT.md\` (L1) → \`lessons.md\` (L3) →
  \`~/.great_cto/decisions.md\` (L4 cross-project ADR log).
- Run \`great-cto board\` (\`http://localhost:3141\`) for the kanban + metrics
  + memory + agents view.

## Quick links

- \`/start "..."\` — kick off a feature pipeline
- \`/inbox\` — see what needs your decision
- \`/agent-review\` — performance scorecard for agents

`;
  if (writeFile(join(cwd, "AGENTS.md"), agentsBody, dryRun)) out.push("AGENTS.md");
  if (writeFile(join(cwd, "CLAUDE.md"), claudeBody, dryRun)) out.push("CLAUDE.md");
  return out;
}

// ── Main entry ─────────────────────────────────────────────────────────────

export async function runAdapt(args: AdaptArgs): Promise<number> {
  const meta = readProjectMeta(args.cwd);
  if (!meta.hasGreatCto) {
    console.error("FAIL: no .great_cto/PROJECT.md found.");
    console.error("Run `npx great-cto init` first to bootstrap the project.");
    return 1;
  }

  console.log(`great-cto adapt → claude${args.dryRun ? " (dry-run)" : ""}`);
  console.log(`  archetype: ${meta.archetype}  compliance: ${meta.compliance.join(", ") || "none"}`);
  console.log("");

  const written = adaptClaude(args.cwd, meta, args.dryRun);

  if (!args.dryRun) {
    console.log("");
    console.log(`✓ generated ${written.length} file(s).`);
    console.log(`  Re-run after editing .great_cto/PROJECT.md to refresh.`);
  }
  return 0;
}
