// great-cto adapt — platform config generator.
//
// Writes platform-native config files derived from a shared core. Lets a
// single great_cto installation work transparently with Claude Code, OpenAI
// Codex CLI, Cursor, Aider, and Continue. AGENTS.md is the de-facto cross-
// platform standard (used verbatim by Codex; consumed as fallback by most
// others) so it forms the shared core.
//
// Usage:
//   great-cto adapt --platform claude     CLAUDE.md
//   great-cto adapt --platform codex      AGENTS.md
//   great-cto adapt --platform cursor     .cursorrules + .cursor/rules/*.mdc
//   great-cto adapt --platform aider      .aider.conf.yml + CONVENTIONS.md
//   great-cto adapt --platform continue   .continue/rules.md
//   great-cto adapt --platform all        all of the above
//   great-cto adapt --dry-run             show what would be written
//
// Each adapter writes ONLY platform-native files. All share the AGENTS.md
// core text via getAgentsCore(). To customize per-project, edit
// .great_cto/PROJECT.md (archetype, owners, compliance) — adapt re-derives.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

export type Platform = "claude" | "codex" | "cursor" | "aider" | "continue" | "all";

export interface AdaptArgs {
  platform: Platform;
  dryRun: boolean;
  cwd: string;
}

interface ProjectMeta {
  archetype: string;
  compliance: string[];
  owners: string;
  hasGreatCto: boolean;
}

function readProjectMeta(cwd: string): ProjectMeta {
  const projectMd = join(cwd, ".great_cto", "PROJECT.md");
  if (!existsSync(projectMd)) {
    return { archetype: "unknown", compliance: [], owners: "", hasGreatCto: false };
  }
  const text = readFileSync(projectMd, "utf8");
  const archetype = (text.match(/^primary:\s*(\S+)/m)?.[1] ?? "unknown").trim();
  const complianceLine = text.match(/^compliance:\s*(.+)$/m)?.[1] ?? "";
  const compliance = complianceLine
    .split(/[,\s]+/)
    .map(s => s.trim())
    .filter(Boolean);
  const owners = (text.match(/^owners?:\s*(.+)$/m)?.[1] ?? "").trim();
  return { archetype, compliance, owners, hasGreatCto: true };
}

/**
 * Common AGENTS.md content used across platforms.
 * Codex CLI reads this verbatim. Cursor / Aider / Claude Code embed it.
 */
function getAgentsCore(meta: ProjectMeta): string {
  const compliance = meta.compliance.length > 0
    ? meta.compliance.map(c => `- ${c}`).join("\n")
    : "_(none auto-detected — set in .great_cto/PROJECT.md)_";

  return `# AGENTS.md

> This file is the cross-tool agent contract. It is consumed by OpenAI Codex
> CLI, Claude Code, Cursor, Aider, Continue, and any other AGENTS.md-aware
> tooling. Generated by \`great-cto adapt\` — re-run after editing
> \`.great_cto/PROJECT.md\`.

## Project context

- **Archetype:** ${meta.archetype}
- **Compliance gates:**
${compliance.split("\n").map(l => "  " + l).join("\n")}
- **Owners:** ${meta.owners || "_(unset)_"}

## How agents should work in this repo

1. **Before touching code** — read \`.great_cto/PROJECT.md\` (archetype +
   constraints) and \`.great_cto/lessons.md\` if present (past mistakes).
2. **Before proposing a fix** — query \`~/.great_cto/decisions.md\` for ADRs
   on related topics. Solved problems should stay solved.
3. **Before merging** — run \`npx great-cto ci\` locally. Same gate as CI.
4. **On failure / incident** — append to \`.great_cto/lessons.md\`. After 3
   occurrences across projects, \`/crystallize\` promotes to global pattern.

## Required gates (do not bypass)

| Gate | When | Owner |
|---|---|---|
| security-officer | Any change touching auth, payments, PII | @security |
| qa-engineer | Any feature merge | @qa |
| performance-engineer | Any change to hot path | @perf |
| db-migration-reviewer | Any \`migrations/\` change | @data |

Override with \`/waiver\` and a written reason. Auto-expires in 14 days.

## Available tools (via MCP)

When this repo is opened in any MCP-capable tool, \`great-cto mcp\` exposes:

- \`scan\` — OWASP LLM Top 10 + 24 rules · returns findings
- \`list_rules\` — full rule catalogue
- \`detect_archetype\` — archetype + compliance for any path
- \`estimate_cost\` — LLM vs human time estimate for a task
- \`query_decisions\` — search ADR log

Configure your client to launch:
\`\`\`bash
npx great-cto mcp
\`\`\`

## Style + conventions

- Tests **before** implementation (RED → GREEN → REFACTOR). Coverage 80%+ default.
- Conventional commits: \`feat\` / \`fix\` / \`docs\` / \`refactor\` / \`test\` / \`chore\`.
- One concern per PR. Refactors and behaviour changes are separate PRs.
- No secrets in code. \`great-cto scan\` blocks ~13 patterns by default.

## Out of scope

Do not invent business decisions. If the spec is ambiguous, ask. Do not skip
gates "because it's just a small change" — that's the path to incidents.

---

_Generated by \`great-cto@${getCliVersion()}\` adapt at ${new Date().toISOString().slice(0, 10)}_
`;
}

function getCliVersion(): string {
  try {
    const here = dirname(new URL(import.meta.url).pathname);
    const pkg = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf8"));
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
}

function writeFile(path: string, content: string, dryRun: boolean): boolean {
  if (dryRun) {
    console.log(`would write: ${path} (${content.length} bytes)`);
    return false;
  }
  mkdirSync(dirname(path), { recursive: true });
  const existed = existsSync(path);
  writeFileSync(path, content);
  console.log(`  ${existed ? "✎ updated" : "✓ wrote"}  ${path}`);
  return true;
}

// ── Per-platform adapters ──────────────────────────────────────────────────

function adaptClaude(cwd: string, meta: ProjectMeta, dryRun: boolean): string[] {
  // Claude Code reads CLAUDE.md (or AGENTS.md as fallback). We write both
  // for maximum compat — projects with CLAUDE.md already get a top-level
  // reference, and AGENTS.md unlocks any AGENTS.md-aware tool simultaneously.
  const out: string[] = [];
  const agentsBody = getAgentsCore(meta);
  const claudeBody = `# CLAUDE.md

> Project guidance for Claude Code. The full agent contract lives in
> \`AGENTS.md\` — please read that first. This file adds Claude-Code-specific
> overrides only.

## Cross-tool contract

See [AGENTS.md](./AGENTS.md) for the full project context, gates, and
conventions. Generated by \`great-cto adapt\`.

## Claude Code specifics

- The great_cto plugin orchestrates 34 specialist agents — pipeline runs
  through \`/start\`, \`/inbox\`, \`/save\`, etc.
- Memory is layered: \`.great_cto/PROJECT.md\` (L1) → \`lessons.md\` (L3) →
  \`~/.great_cto/decisions.md\` (L4 cross-project ADR log).
- Run \`great-cto board\` (\`http://localhost:3141\`) for the kanban + metrics
  + memory + agents view.

## Quick links

- ${"`"}/start "..."${"`"} — kick off a feature pipeline
- ${"`"}/inbox${"`"} — see what needs your decision
- ${"`"}/agent-review${"`"} — performance scorecard for agents

`;
  if (writeFile(join(cwd, "AGENTS.md"), agentsBody, dryRun)) out.push("AGENTS.md");
  if (writeFile(join(cwd, "CLAUDE.md"), claudeBody, dryRun)) out.push("CLAUDE.md");
  return out;
}

function adaptCodex(cwd: string, meta: ProjectMeta, dryRun: boolean): string[] {
  // OpenAI Codex CLI reads AGENTS.md. We write only that — Codex doesn't
  // currently consume CLAUDE.md / .cursorrules.
  const out: string[] = [];
  if (writeFile(join(cwd, "AGENTS.md"), getAgentsCore(meta), dryRun)) out.push("AGENTS.md");
  return out;
}

function adaptCursor(cwd: string, meta: ProjectMeta, dryRun: boolean): string[] {
  // Cursor reads .cursorrules (legacy single file) and .cursor/rules/*.mdc
  // (modern modular). Write both for compat.
  const out: string[] = [];
  const rulesContent = `# Cursor rules — auto-generated by great-cto adapt
# See AGENTS.md for the full agent contract; this file is the Cursor-native
# subset focusing on inline-completion and chat behaviour.

archetype: ${meta.archetype}
compliance:
${meta.compliance.map(c => `  - ${c}`).join("\n") || "  - none"}

## Behaviour

Before suggesting code changes:
- Read \`AGENTS.md\` for repo-wide conventions
- Read \`.great_cto/PROJECT.md\` for archetype constraints
- Check \`~/.great_cto/decisions.md\` for prior ADRs on the topic

## Gates that block merges (do not bypass)

- security-officer: auth/payments/PII changes
- qa-engineer: feature merges
- db-migration-reviewer: any migrations/ change

## Style

- TDD: tests RED → implementation GREEN → refactor
- Conventional commits
- One concern per PR
`;

  const mdcContent = `---
description: great_cto archetype + compliance contract
globs: ["**/*"]
alwaysApply: true
---

This repo is a **${meta.archetype}** project. Compliance gates:
${meta.compliance.map(c => `- ${c}`).join("\n") || "- none"}

Read \`AGENTS.md\` and \`.great_cto/PROJECT.md\` before proposing changes.
Run \`npx great-cto ci\` before pushing.
`;

  if (writeFile(join(cwd, ".cursorrules"), rulesContent, dryRun)) out.push(".cursorrules");
  if (writeFile(join(cwd, ".cursor", "rules", "great-cto.mdc"), mdcContent, dryRun)) out.push(".cursor/rules/great-cto.mdc");
  if (writeFile(join(cwd, "AGENTS.md"), getAgentsCore(meta), dryRun)) out.push("AGENTS.md");
  return out;
}

function adaptAider(cwd: string, meta: ProjectMeta, dryRun: boolean): string[] {
  // Aider reads .aider.conf.yml for settings and CONVENTIONS.md (or files
  // listed in read: arrays) for context.
  const out: string[] = [];
  const conf = `# .aider.conf.yml — auto-generated by great-cto adapt
# Aider config. Run aider in this dir and these settings apply.

# Always include AGENTS.md and PROJECT.md as context
read:
  - AGENTS.md
  - .great_cto/PROJECT.md

# Auto-test after edits
auto-test: true
test-cmd: "npx great-cto ci --severity high"

# Pretty output
pretty: true

# Conventional commits
commit-prompt: "Use conventional commit format: feat/fix/docs/refactor/test/chore"

# Archetype: ${meta.archetype}
# Compliance: ${meta.compliance.join(", ") || "none"}
`;

  const conventions = `# CONVENTIONS.md

> This is the Aider-native conventions file. The cross-tool agent contract
> lives in \`AGENTS.md\` — please read that for full context.

## Quick rules

- **Archetype:** ${meta.archetype}
- **Compliance gates:** ${meta.compliance.join(", ") || "_(none)_"}

### Process
1. Tests first (TDD)
2. One concern per PR
3. Conventional commits
4. Run \`npx great-cto ci\` before push

### Style
- No secrets in code (\`great-cto scan\` enforces this)
- Read \`.great_cto/PROJECT.md\` before suggesting architectural changes
- Read \`~/.great_cto/decisions.md\` for prior ADRs
`;
  if (writeFile(join(cwd, ".aider.conf.yml"), conf, dryRun)) out.push(".aider.conf.yml");
  if (writeFile(join(cwd, "CONVENTIONS.md"), conventions, dryRun)) out.push("CONVENTIONS.md");
  if (writeFile(join(cwd, "AGENTS.md"), getAgentsCore(meta), dryRun)) out.push("AGENTS.md");
  return out;
}

function adaptContinue(cwd: string, meta: ProjectMeta, dryRun: boolean): string[] {
  const out: string[] = [];
  const rulesContent = `# Continue rules — generated by great-cto adapt

## Project context

Archetype: **${meta.archetype}**.
Compliance: ${meta.compliance.join(", ") || "none"}.
Read \`AGENTS.md\` for the full contract.

## Behaviour

- Run \`npx great-cto ci\` before pushing
- Don't bypass gates (security / qa / db-migration)
- Append lessons to \`.great_cto/lessons.md\` after incidents
`;
  if (writeFile(join(cwd, ".continue", "rules.md"), rulesContent, dryRun)) out.push(".continue/rules.md");
  if (writeFile(join(cwd, "AGENTS.md"), getAgentsCore(meta), dryRun)) out.push("AGENTS.md");
  return out;
}

// ── Main entry ─────────────────────────────────────────────────────────────

export async function runAdapt(args: AdaptArgs): Promise<number> {
  const meta = readProjectMeta(args.cwd);
  if (!meta.hasGreatCto) {
    console.error("FAIL: no .great_cto/PROJECT.md found.");
    console.error("Run `npx great-cto init` first to bootstrap the project.");
    return 1;
  }

  const platforms: Exclude<Platform, "all">[] =
    args.platform === "all"
      ? ["claude", "codex", "cursor", "aider", "continue"]
      : [args.platform];

  console.log(`great-cto adapt → ${platforms.join(", ")}${args.dryRun ? " (dry-run)" : ""}`);
  console.log(`  archetype: ${meta.archetype}  compliance: ${meta.compliance.join(", ") || "none"}`);
  console.log("");

  const written: string[] = [];
  for (const p of platforms) {
    console.log(`▸ ${p}`);
    const adapter = {
      claude: adaptClaude,
      codex: adaptCodex,
      cursor: adaptCursor,
      aider: adaptAider,
      continue: adaptContinue,
    }[p];
    const out = adapter(args.cwd, meta, args.dryRun);
    written.push(...out);
  }

  if (!args.dryRun) {
    console.log("");
    console.log(`✓ generated ${written.length} file(s) for ${platforms.length} platform(s).`);
    console.log(`  Re-run after editing .great_cto/PROJECT.md to refresh.`);
  }
  return 0;
}
