// great-cto adapt — AI config generator.
//
// Writes CLAUDE.md + AGENTS.md from .great_cto/PROJECT.md context.
// Also generates cross-AI configs for Cursor, Copilot, Windsurf, Aider
// when ai_tools is set in PROJECT.md.
//
// Usage:
//   great-cto adapt            Generate all configs (reads ai_tools from PROJECT.md)
//   great-cto adapt --dry-run  Show what would be written

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

export type Platform = "claude";

/** AI tools that great-cto can generate config files for. */
export type AiTool = "claude-code" | "cursor" | "copilot" | "windsurf" | "aider" | "codex";

export interface AdaptArgs {
  platform: Platform;
  dryRun: boolean;
  cwd: string;
}

interface ProjectMeta {
  archetype: string;
  compliance: string[];
  owners: string;
  hasGreatCto: boolean;
  aiTools: AiTool[];
  projectName: string;
}

const VALID_AI_TOOLS: AiTool[] = ["claude-code", "cursor", "copilot", "windsurf", "aider", "codex"];

function parseAiTools(text: string): AiTool[] {
  const line = text.match(/^ai_tools:\s*(.+)$/m)?.[1] ?? "";
  // Support: [claude-code, cursor] or claude-code, cursor or claude-code
  const raw = line.replace(/[\[\]]/g, "").split(/[,\s]+/).map(s => s.trim()).filter(Boolean);
  return raw.filter((t): t is AiTool => VALID_AI_TOOLS.includes(t as AiTool));
}

function readProjectMeta(cwd: string): ProjectMeta {
  const projectMd = join(cwd, ".great_cto", "PROJECT.md");
  if (!existsSync(projectMd)) {
    return { archetype: "unknown", compliance: [], owners: "", hasGreatCto: false, aiTools: ["claude-code"], projectName: "project" };
  }
  const text = readFileSync(projectMd, "utf8");
  const archetype = (text.match(/^primary:\s*(\S+)/m)?.[1] ?? "unknown").trim();
  const complianceLine = text.match(/^compliance:\s*(.+)$/m)?.[1] ?? "";
  const compliance = complianceLine
    .split(/[,\s]+/)
    .map(s => s.trim())
    .filter(Boolean);
  const owners = (text.match(/^owners?:\s*(.+)$/m)?.[1] ?? "").trim();
  const aiTools = parseAiTools(text);
  // Infer project name from first H1 heading
  const projectName = (text.match(/^#\s+(.+)$/m)?.[1] ?? "project").trim();
  return { archetype, compliance, owners, hasGreatCto: true, aiTools: aiTools.length > 0 ? aiTools : ["claude-code"], projectName };
}

/**
 * Project Constitution — universal hard constraints injected into every AI config.
 * Inspired by Spec Driven Development (FredAntB/Spec-Driven-Development).
 */
function getConstitutionBlock(meta: ProjectMeta): string {
  const hasSpec = existsSync(join(process.cwd(), "requirements.md"));
  const specSection = hasSpec ? `
## Spec files (source of truth)

  requirements.md  — What the system must do
  design.md        — How the system is structured
  tasks.md         — Ordered implementation plan

MANDATORY BEFORE ANY ACTION:
  0. If CONTEXT.md exists, read it first — it has session state
  1. Read requirements.md — understand what is in scope
  2. Read design.md — understand how it is structured
  3. Read tasks.md — find the next incomplete [ ] task
` : `
## Session context

  0. If CONTEXT.md exists, read it first — it has the active task and session state
  1. Read .great_cto/PROJECT.md — archetype, compliance gates, team mode
  2. Read .great_cto/lessons.md if present — past mistakes and patterns
`;

  return `
═══════════════════════════════════════════════════════════
PROJECT CONSTITUTION — ${meta.projectName.toUpperCase()}
Generated by great-cto adapt · ${new Date().toISOString().slice(0, 10)}
═══════════════════════════════════════════════════════════
${specSection}
HARD CONSTRAINTS (no exceptions):
  ✗ Never implement requirements not explicitly defined in requirements.md
  ✗ Never alter the data model without updating design.md first
  ✗ Never mark a task [x] without verifying its acceptance criterion
  ✗ Never create files not listed or implied in design.md
  ✗ Never guess when a requirement is ambiguous — ask instead
  ✗ Never skip gates (security-officer, qa-engineer) — use /waiver with reason

AFTER COMPLETING A TASK:
  1. Run the verification step listed in tasks.md (or acceptance criterion)
  2. Mark the task [x] in tasks.md
  3. Update CONTEXT.md resume block with the next active task
  4. Record any divergences from design.md in CONTEXT.md

IF IMPLEMENTATION MUST DEVIATE FROM DESIGN:
  1. Stop immediately
  2. Describe the conflict clearly
  3. Wait for explicit approval
  4. Update design.md FIRST, then implement
═══════════════════════════════════════════════════════════
`;
}

/**
 * AGENTS.md — Claude Code reads this as the cross-tool agent contract.
 */
function getAgentsCore(meta: ProjectMeta): string {
  const compliance = meta.compliance.length > 0
    ? meta.compliance.map(c => `- ${c}`).join("\n")
    : "_(none auto-detected — set in .great_cto/PROJECT.md)_";

  const constitution = getConstitutionBlock(meta);

  return `# AGENTS.md
${constitution}

> Project agent contract for Claude Code. Generated by \`great-cto adapt\` —
> re-run after editing \`.great_cto/PROJECT.md\`.

## Project context

- **Archetype:** ${meta.archetype}
- **Compliance gates:**
${compliance.split("\n").map(l => "  " + l).join("\n")}
- **Owners:** ${meta.owners || "_(unset)_"}

## How agents should work in this repo

1. **Before touching code** — read \`.great_cto/PROJECT.md\` (archetype +
   constraints) and \`.great_cto/lessons.md\` if present (past mistakes).
2. **Before proposing a fix** — query \`~/.great_cto/decisions.md\` for ADRs
   on related topics. Solved problems should stay solved.
3. **Before merging** — run \`npx great-cto ci\` locally. Same gate as CI.
4. **On failure / incident** — append to \`.great_cto/lessons.md\`. After 3
   occurrences across projects, \`/crystallize\` promotes to global pattern.

## Required gates (do not bypass)

| Gate | When | Owner |
|---|---|---|
| security-officer | Any change touching auth, payments, PII | @security |
| qa-engineer | Any feature merge | @qa |
| performance-engineer | Any change to hot path | @perf |
| db-migration-reviewer | Any \`migrations/\` change | @data |

Override with \`/waiver\` and a written reason. Auto-expires in 14 days.

## Available tools (via MCP)

When this repo is opened in Claude Code, \`great-cto mcp\` exposes:

- \`scan\` — OWASP LLM Top 10 + 24 rules · returns findings
- \`list_rules\` — full rule catalogue
- \`detect_archetype\` — archetype + compliance for any path
- \`estimate_cost\` — LLM vs human time estimate for a task
- \`query_decisions\` — search ADR log

Configure Claude Code to launch:
\`\`\`bash
npx great-cto mcp
\`\`\`

## Subagent routing (do not default to general-purpose)

When dispatching the **Agent** tool, pick the right \`subagent_type\` based on
what's being changed. \`general-purpose\` is a fallback, **not** the default —
using it for pattern-matched work silently skips specialist review.

| Trigger (file pattern OR topic in prompt) | Use \`subagent_type:\` |
|---|---|
| \`migrations/\`, \`schema.sql\`, ORM migration files | \`db-migration-reviewer\` |
| \`auth/\`, OAuth/SAML/JWT, login flow, password reset | \`security-officer\` |
| Payment endpoints, \`stripe.\`, webhooks, refund flow | \`pci-reviewer\` |
| Prompts in \`prompts/\`, RAG, tool definitions, LLM-facing strings | \`ai-security-reviewer\` |
| Eval suites, golden citation tests, prompt regression | \`ai-eval-engineer\` |
| Play Store, App Store, iOS/Android release | \`mobile-store-reviewer\` |
| API contract: OpenAPI, GraphQL schema, webhook signatures | \`api-platform-reviewer\` |
| Voice/IVR/telephony, Twilio, recording-consent, TCPA | \`voice-ai-reviewer\` |
| Clinical / SaMD / FDA / FHIR / PHI | \`ai-clinical-reviewer\`, \`fda-reviewer\` |
| Wearable telemetry, HealthKit, Health Connect, Garmin, Samsung Health, fitness AI, mental health AI, nutrition AI, supplement AI, physician HITL | \`digital-health-reviewer\` |
| HR-AI, hiring, AEDT, resume screening | \`hr-ai-reviewer\` |
| Infra-as-code: Terraform / Helm / CDK / Pulumi | \`infra-reviewer\` |
| Performance regression, hot path, p99 budgets | \`performance-engineer\` |
| Browser extension manifest, MV3 permissions | \`web-store-reviewer\` |
| New feature implementation (TDD) | \`senior-dev\` |
| Architecture decisions, ADRs, scaling questions | \`architect\` |
| Planning a feature into tasks (Beads), dependency graph | \`pm\` |
| QA report after impl, coverage + acceptance | \`qa-engineer\` |
| Deploy / canary / rollback / SLO | \`devops\` |
| Production incident triage, P0 postmortem | \`l3-support\` |
| Pattern extraction from session, retro to \`lessons.md\` | \`continuous-learner\` |

Rule of thumb: if a file pattern or topic matches above, use that specialist
**before** falling back to \`general-purpose\`. Specialist agents catch
domain-specific bugs (race conditions in migrations, prompt-injection vectors,
TCPA violations) that a generalist won't flag.

When in doubt, run two agents in parallel: the specialist + general-purpose,
and reconcile their outputs.

## Style + conventions

- Tests **before** implementation (RED → GREEN → REFACTOR). Coverage 80%+ default.
- Conventional commits: \`feat\` / \`fix\` / \`docs\` / \`refactor\` / \`test\` / \`chore\`.
- One concern per PR. Refactors and behaviour changes are separate PRs.
- No secrets in code. \`great-cto scan\` blocks ~13 patterns by default.

## Out of scope

Do not invent business decisions. If the spec is ambiguous, ask. Do not skip
gates "because it's just a small change" — that's the path to incidents.

---

_Generated by \`great-cto@${getCliVersion()}\` adapt at ${new Date().toISOString().slice(0, 10)}_
`;
}

// ── Cross-AI config generators ─────────────────────────────────────────────

function getCursorrules(meta: ProjectMeta): string {
  const constitution = getConstitutionBlock(meta);
  return `${constitution}

# .cursorrules — Cursor AI configuration for ${meta.projectName}
# Generated by great-cto adapt · ${new Date().toISOString().slice(0, 10)}

## Project context

- **Archetype:** ${meta.archetype}
- **Compliance:** ${meta.compliance.join(", ") || "none"}
- **Stack:** See .great_cto/PROJECT.md

## Coding conventions

- TypeScript strict mode — no \`any\` without explanatory comment
- ESM modules only (.mjs / "type":"module")
- Conventional commits: feat / fix / docs / refactor / test / chore
- Tests before implementation (RED → GREEN → REFACTOR), 80%+ coverage
- One concern per PR — refactors and behaviour changes are separate PRs

## Agent routing

For complex tasks, prefer the great_cto agent pipeline (via Claude Code):
- Architecture decisions → \`architect\` agent
- Feature planning → \`pm\` agent
- Implementation → \`senior-dev\` agent
- Security review → \`security-officer\` agent

See AGENTS.md for the full routing table.
`;
}

function getCopilotInstructions(meta: ProjectMeta): string {
  const constitution = getConstitutionBlock(meta);
  return `${constitution}

# GitHub Copilot Instructions for ${meta.projectName}
# Generated by great-cto adapt · ${new Date().toISOString().slice(0, 10)}

## Project context

- **Archetype:** ${meta.archetype}
- **Compliance gates:** ${meta.compliance.join(", ") || "none"}
- **Read first:** CONTEXT.md (session state), requirements.md (scope)

## Code style

- TypeScript strict mode, ESM-only
- Conventional commits
- Test-first development — write tests before implementation
- No secrets in code — great-cto scan blocks ~13 patterns

## What NOT to do

- Do not implement features not in requirements.md
- Do not alter data models without updating design.md
- Do not generate placeholder files with TODO tokens
- Do not guess ambiguous requirements — surface them for human decision
`;
}

function getWindsurfrules(meta: ProjectMeta): string {
  const constitution = getConstitutionBlock(meta);
  return `${constitution}

# .windsurfrules — Windsurf AI configuration for ${meta.projectName}
# Generated by great-cto adapt · ${new Date().toISOString().slice(0, 10)}

## Session startup

1. Read CONTEXT.md — resume active task from resume block
2. Read requirements.md — understand scope
3. Read design.md — understand structure
4. Find next incomplete [ ] task in tasks.md

## Project context

- Archetype: ${meta.archetype}
- Compliance: ${meta.compliance.join(", ") || "none"}
- Spec files: requirements.md / design.md / tasks.md

## Hard rules

- Never implement beyond requirements.md scope
- Never skip the CONTEXT.md update at session end
- Run verification step before marking any task complete
`;
}

function getAiderConf(meta: ProjectMeta): string {
  return `# .aider.conf.yml — Aider configuration for ${meta.projectName}
# Generated by great-cto adapt · ${new Date().toISOString().slice(0, 10)}

# Read these files as context at startup
read:
  - CONTEXT.md
  - requirements.md
  - design.md
  - tasks.md
  - .great_cto/PROJECT.md

# Commit message format
commit-prompt: |
  Write a conventional commit message (feat/fix/docs/refactor/test/chore).
  Be specific about what changed and why.
  Never mention private project names — use <private-project> placeholder.

# Conventions
auto-commits: false
dirty-commits: false
`;
}

// ── Codex adapter helpers ──────────────────────────────────────────────────

/**
 * hooks.json content for ~/.codex/skills/great_cto/hooks.json.
 *
 * Phase 0 findings (2026-06-04, confirmed against Codex Desktop binary):
 * - Hook events: PreToolUse, PostToolUse, SessionStart, SubagentStart,
 *   SubagentStop, PreCompact, PostCompact, UserPromptSubmit, PermissionRequest.
 * - stdin payload: same keys as Claude Code (tool_name, tool_input, is_error).
 * - block/deny: hookSpecificOutput.permissionDecision (same struct as CC)
 *   confirmed by binary string literals.
 * - Hooks enabled by [features].hooks = true in config.toml.
 *
 * @param skillDir - absolute path to ~/.codex/skills/great_cto (used to build hook commands)
 */
export function getCodexHooksJson(skillDir: string): string {
  const s = skillDir; // shorthand
  return JSON.stringify({
    "SessionStart": [
      {
        "hooks": [
          { "command": `node "${s}/scripts/hooks/quota-check.mjs" 2>/dev/null || true`, "timeout": 15 }
        ]
      }
    ],
    "PreToolUse": [
      {
        "matcher": "computer|bash|shell",
        "hooks": [
          { "command": `node "${s}/scripts/hooks/orchestrator-check.mjs" 2>/dev/null || true`, "timeout": 5 },
          { "command": `node "${s}/scripts/hooks/cost-guard.mjs" 2>/dev/null || true`, "timeout": 5 }
        ]
      },
      {
        "matcher": "edit|write|str_replace_editor|computer",
        "hooks": [
          { "command": `node "${s}/scripts/hooks/secret-scan.mjs" 2>/dev/null || true`, "timeout": 8 }
        ]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "edit|write|str_replace_editor",
        "hooks": [
          { "command": `node "${s}/scripts/hooks/format-check.mjs" 2>/dev/null; true`, "timeout": 12, "async": true },
          { "command": `node "${s}/scripts/hooks/tool-failure.mjs" 2>/dev/null || true`, "timeout": 3, "async": true }
        ]
      },
      {
        "matcher": "",
        "hooks": [
          { "command": `node "${s}/scripts/hooks/tool-failure.mjs" 2>/dev/null || true`, "timeout": 3, "async": true }
        ]
      }
    ]
  }, null, 2);
}

/**
 * config.toml fragment to merge into ~/.codex/config.toml.
 * Adds: [features].hooks=true, [mcp_servers.great_cto], [agents.great_cto_skill].
 * Written as a separate file (.codex/great_cto.toml) since merging TOML is
 * non-trivial; installer prints merge instructions.
 */
function getCodexConfigFragment(meta: ProjectMeta): string {
  return `# great_cto Codex integration — generated by great-cto adapt
# Merge this into ~/.codex/config.toml or copy the sections manually.
# Generated: ${new Date().toISOString().slice(0, 10)}

[features]
hooks = true

[mcp_servers.great_cto]
command = "npx"
args = ["great-cto@latest", "mcp"]
# Set startup timeout generously — npx downloads on first run
startup_timeout_sec = 60

[mcp_servers.great_cto.env]
# Point hooks at the skill dir so hook scripts resolve correctly.
CODEX_SKILL_DIR = "${process.env.HOME ?? "~"}/.codex/skills/great_cto"

# Agents exposed via MCP (great_cto specialist fleet)
# Codex will use these as subagent personalities via the [agents] table.
# Full 57-agent routing is handled inside AGENTS.md / SKILL.md.
[agents.great_cto_architect]
description = "Deep architectural reasoning, ADRs, cross-cutting design decisions"

[agents.great_cto_senior_dev]
description = "Feature implementation with TDD — RED→GREEN→REFACTOR"

[agents.great_cto_qa_engineer]
description = "QA reports, coverage, regression check after implementation"

[agents.great_cto_security_officer]
description = "Security audit — OWASP Top 10, auth, PII, secrets"

[agents.great_cto_devops]
description = "Deploy, canary rollout, rollback, SLO monitoring"

[agents.great_cto_pm]
description = "Feature decomposition into tasks, timeline, dependency graph"

# Archetype: ${meta.archetype}
# Compliance: ${meta.compliance.join(", ") || "none"}
# Re-run great-cto adapt --platform codex to refresh.
`;
}

function getCliVersion(): string {
  try {
    const here = dirname(new URL(import.meta.url).pathname);
    const pkg = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf8"));
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
}

function writeFile(path: string, content: string, dryRun: boolean): boolean {
  if (dryRun) {
    console.log(`would write: ${path} (${content.length} bytes)`);
    return false;
  }
  mkdirSync(dirname(path), { recursive: true });
  const existed = existsSync(path);
  writeFileSync(path, content);
  console.log(`  ${existed ? "✎ updated" : "✓ wrote"}  ${path}`);
  return true;
}

// ── Claude Code adapter ────────────────────────────────────────────────────

function adaptClaude(cwd: string, meta: ProjectMeta, dryRun: boolean): string[] {
  const out: string[] = [];
  const agentsBody = getAgentsCore(meta);
  const claudeBody = `# CLAUDE.md

> Project guidance for Claude Code. The full agent contract lives in
> \`AGENTS.md\` — please read that first. This file adds Claude Code-specific
> overrides only.

## Cross-tool contract

See [AGENTS.md](./AGENTS.md) for the full project context, gates, and
conventions. Generated by \`great-cto adapt\`.

## Claude Code specifics

- The great_cto plugin orchestrates specialist agents — pipeline runs
  through \`/start\`, \`/inbox\`, \`/save\`, \`/spec\`, etc.
- Memory is layered: \`.great_cto/PROJECT.md\` (L1) → \`lessons.md\` (L3) →
  \`~/.great_cto/decisions.md\` (L4 cross-project ADR log).
- Run \`great-cto board\` (\`http://localhost:3141\`) for the kanban + metrics
  + memory + agents view.

## Quick links

- \`/spec\` — interview → requirements.md + design.md + tasks.md
- \`/start "..."\` — kick off a feature pipeline
- \`/inbox\` — see what needs your decision
- \`/agent-review\` — performance scorecard for agents

`;
  if (writeFile(join(cwd, "AGENTS.md"), agentsBody, dryRun)) out.push("AGENTS.md");
  if (writeFile(join(cwd, "CLAUDE.md"), claudeBody, dryRun)) out.push("CLAUDE.md");

  // Cross-AI config files based on ai_tools in PROJECT.md
  for (const tool of meta.aiTools) {
    switch (tool) {
      case "cursor": {
        const path = join(cwd, ".cursorrules");
        if (writeFile(path, getCursorrules(meta), dryRun)) out.push(".cursorrules");
        break;
      }
      case "copilot": {
        const path = join(cwd, ".github", "copilot-instructions.md");
        if (writeFile(path, getCopilotInstructions(meta), dryRun)) out.push(".github/copilot-instructions.md");
        break;
      }
      case "windsurf": {
        const path = join(cwd, ".windsurfrules");
        if (writeFile(path, getWindsurfrules(meta), dryRun)) out.push(".windsurfrules");
        break;
      }
      case "aider": {
        const path = join(cwd, ".aider.conf.yml");
        if (writeFile(path, getAiderConf(meta), dryRun)) out.push(".aider.conf.yml");
        break;
      }
      case "codex": {
        // Write hooks.json + config.toml fragment to .codex/ (project-scoped, trusted)
        const defaultSkillDir = `${process.env.HOME ?? "~"}/.codex/skills/great_cto`;
        const hooksPath = join(cwd, ".codex", "hooks.json");
        const configPath = join(cwd, ".codex", "great_cto.toml");
        if (writeFile(hooksPath, getCodexHooksJson(defaultSkillDir), dryRun)) out.push(".codex/hooks.json");
        if (writeFile(configPath, getCodexConfigFragment(meta), dryRun)) out.push(".codex/great_cto.toml");
        if (!dryRun) {
          console.log("  ⚠  Codex: merge .codex/great_cto.toml sections into ~/.codex/config.toml");
          console.log("     Then restart Codex to activate hooks and MCP server.");
        }
        break;
      }
      case "claude-code":
        // Already handled above (CLAUDE.md + AGENTS.md)
        break;
    }
  }

  return out;
}

// ── Main entry ─────────────────────────────────────────────────────────────

export async function runAdapt(args: AdaptArgs): Promise<number> {
  const meta = readProjectMeta(args.cwd);
  if (!meta.hasGreatCto) {
    console.error("FAIL: no .great_cto/PROJECT.md found.");
    console.error("Run `npx great-cto init` first to bootstrap the project.");
    return 1;
  }

  const toolsList = meta.aiTools.join(", ");
  console.log(`great-cto adapt → ${toolsList}${args.dryRun ? " (dry-run)" : ""}`);
  console.log(`  archetype: ${meta.archetype}  compliance: ${meta.compliance.join(", ") || "none"}`);
  console.log(`  ai_tools:  ${toolsList}`);
  console.log("");

  const written = adaptClaude(args.cwd, meta, args.dryRun);

  if (!args.dryRun) {
    console.log("");
    console.log(`✓ generated ${written.length} file(s): ${written.join(", ")}`);
    console.log(`  Re-run after editing .great_cto/PROJECT.md or adding tools to ai_tools: [] to refresh.`);
    if (!meta.aiTools.includes("cursor") && !meta.aiTools.includes("copilot") && !meta.aiTools.includes("windsurf")) {
      console.log(`  Tip: add other AI tools to ai_tools: [] in PROJECT.md to generate .cursorrules, copilot-instructions.md, etc.`);
    }
  }
  return 0;
}
