// Generate .great_cto/PROJECT.md pre-filled from detected stack + archetype.
// Safe: will NOT overwrite an existing PROJECT.md.

import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { DetectionResult } from "./detect.js";
import type { Archetype } from "./archetypes.js";
import { dim, success, warn } from "./ui.js";

export interface BootstrapResult {
  projectMdPath: string;
  created: boolean;
  skippedReason: string | null;
}

export function bootstrap(
  dir: string,
  detection: DetectionResult,
  archetype: Archetype,
  compliance: string[],
): BootstrapResult {
  const greatCtoDir = join(dir, ".great_cto");
  const projectMd = join(greatCtoDir, "PROJECT.md");

  if (existsSync(projectMd)) {
    warn(`.great_cto/PROJECT.md already exists — not overwriting.`);
    return { projectMdPath: projectMd, created: false, skippedReason: "already exists" };
  }

  mkdirSync(greatCtoDir, { recursive: true });

  const title = inferProjectTitle(dir);
  const stackLine = detection.stack.length > 0 ? detection.stack.join(", ") : "to be defined";
  const complianceLine = compliance.length > 0 ? compliance.join(", ") : "none";
  const teamSize = 1;                 // MVP default — user edits later
  const approvalLevel = "gates-only"; // default per README

  const content = `# ${title}

> Auto-generated by \`great-cto init\` on ${new Date().toISOString().slice(0, 10)}.
> Edit freely — this file is yours. Re-run \`npx great-cto init\` won't overwrite it.

## Project

primary: ${archetype}
stack: ${stackLine}
languages: ${detection.languages.join(", ") || "to be defined"}
package-manager: ${detection.packageManager ?? "none"}

## Phase

phase: implementation

> Values: planning | implementation | review | release. SessionStart hook
> loads phase-specific context (skips QA/CSO/perf for planning; skips
> brainstorm/RFC for release). Switch in chat: "move to review phase".

## Team

size: ${teamSize}
mode: solo
approval-level: ${approvalLevel}

## Compliance

frameworks: [${complianceLine}]

## Goals

- <add your primary goal here>
- <add your second goal here>

## Context

- Tests present: ${detection.hasTests ? "yes" : "no"}
- CI configured: ${detection.hasCI ? "yes" : "no"}
- Detected signals: ${JSON.stringify(detection.signals, null, 2).replace(/\n/g, "\n  ")}

## Notes

Generated from stack auto-detection. For a full audit (gap analysis, tech
debt scan, architectural review) run \`/audit\` in Claude Code after install.
`;

  writeFileSync(projectMd, content, "utf-8");
  success(`created .great_cto/PROJECT.md ${dim(`(archetype: ${archetype})`)}`);
  return { projectMdPath: projectMd, created: true, skippedReason: null };
}

function inferProjectTitle(dir: string): string {
  // Prefer package.json name, then directory basename.
  try {
    const pkgPath = join(dir, "package.json");
    if (existsSync(pkgPath)) {
      const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as { name?: string };
      if (pkg.name) return pkg.name;
    }
  } catch { /* ignore */ }
  const parts = dir.split(/[\/\\]/);
  return parts[parts.length - 1] ?? "project";
}
