// Generate .great_cto/PROJECT.md pre-filled from detected stack + archetype.
// Safe: will NOT overwrite an existing PROJECT.md.

import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import type { DetectionResult } from "./detect.js";
import type { Archetype, ProjectSize } from "./archetypes.js";
import { dim, success, warn } from "./ui.js";
import { suggestJurisdictions } from "./jurisdictions.js";
import { compileFlow, renderFlowMd, type FlowResult } from "./flow.js";

export interface BootstrapResult {
  projectMdPath: string;
  created: boolean;
  skippedReason: string | null;
  /** Compiled delivery flow — null when PROJECT.md already existed (not overwriting). */
  flow: FlowResult | null;
}

export function bootstrap(
  dir: string,
  detection: DetectionResult,
  archetype: Archetype,
  compliance: string[],
  detectionMeta?: { confidence: string; alternatives: string[]; rationale?: string },
): BootstrapResult {
  const greatCtoDir = join(dir, ".great_cto");
  const projectMd = join(greatCtoDir, "PROJECT.md");

  if (existsSync(projectMd)) {
    warn(`.great_cto/PROJECT.md already exists — not overwriting.`);
    return { projectMdPath: projectMd, created: false, skippedReason: "already exists", flow: null };
  }

  mkdirSync(greatCtoDir, { recursive: true });

  const title = inferProjectTitle(dir);
  const stackLine = detection.stack.length > 0 ? detection.stack.join(", ") : "to be defined";
  const complianceLine = compliance.length > 0 ? compliance.join(", ") : "none";
  const jurisdictionMatches = suggestJurisdictions(detection);
  const jurisdictionLine = jurisdictionMatches.length > 0
    ? jurisdictionMatches.map((m) => m.jurisdiction).join(", ")
    : "unknown";
  const teamSize = 1;                 // MVP default — user edits later
  const approvalLevel = "gates-only"; // default per README

  // Write CONTEXT.md in the project root (resume-block for all AI agents).
  const contextMdPath = join(dir, "CONTEXT.md");
  if (!existsSync(contextMdPath)) {
    const contextContent = `# CONTEXT.md

> AI session state for all agents. Updated at the end of each session.
> All AI coding tools (Claude Code, Cursor, Copilot, Windsurf, Aider) read this
> before starting work.

## Resume block

**Current task:** _(none — project just initialized)_
**Last session:** ${new Date().toISOString().slice(0, 10)}
**Status:** 🟢 ready to start

## Session log

| Session | Date | Summary | Files changed |
|---------|------|---------|---------------|
| 1 | ${new Date().toISOString().slice(0, 10)} | Project initialized | CONTEXT.md, .great_cto/PROJECT.md |

## Open questions

_(none yet — add questions that need founder/team input before implementation can proceed)_

## Divergences from spec

_(none — record any deviations from design.md here with rationale)_
`;
    writeFileSync(contextMdPath, contextContent, "utf-8");
    success(`created CONTEXT.md ${dim("(session resume block for all AI tools)")}`);
  }

  const content = `# ${title}

> Auto-generated by \`great-cto init\` on ${new Date().toISOString().slice(0, 10)}.
> Edit freely — this file is yours. Re-run \`npx great-cto init\` won't overwrite it.

## Project

primary: ${archetype}
archetype: ${archetype}
project_size: ${detection.projectSize}
stack: ${stackLine}
languages: ${detection.languages.join(", ") || "to be defined"}
package-manager: ${detection.packageManager ?? "none"}
${detectionMeta ? `archetype_confidence: ${detectionMeta.confidence}\n` : ""}${detectionMeta && detectionMeta.alternatives.length > 0 ? `archetype_alternatives: [${detectionMeta.alternatives.join(", ")}]\n` : ""}${detectionMeta?.rationale ? `archetype_rationale: ${detectionMeta.rationale.replace(/\n/g, " ")}\n` : ""}
> \`archetype:\` drives tier/gate selection (see references/security-tiers.md).
> \`project_size:\` is one of nano | small | medium | large | enterprise — agents
> scale gate depth accordingly. Edit either if auto-detection got it wrong.
> \`archetype_confidence:\` is one of high | medium | low | user-specified — when
> < high, /inbox surfaces a warning so you can override before committing.

## Phase

phase: implementation

> Values: planning | implementation | review | release. SessionStart hook
> loads phase-specific context (skips QA/CSO/perf for planning; skips
> brainstorm/RFC for release). Switch in chat: "move to review phase".

## Team

team-size: ${teamSize}
mode: solo
approval-level: ${approvalLevel}
ai_tools: [claude-code]

> \`team-size:\` is read at root level (not nested) by /rfc and other commands.
> \`ai_tools:\` controls which config files \`great-cto adapt\` generates.
> Supported values: claude-code, cursor, copilot, windsurf, aider
> Example: ai_tools: [claude-code, cursor, copilot]

## Compliance

compliance: [${complianceLine}]
jurisdiction: [${jurisdictionLine}]

> \`compliance:\` list drives which checklists security-officer runs.
> \`jurisdiction:\` is auto-detected from README geo/legal signals — edit if wrong.
> Supported codes: eu · us · us-ca · uk · in · br · au · sg
> See docs/jurisdiction-compliance.md for what each code activates.


## Memory & Query Rule

> Before reading source files, agents should query memory layers in this order:
> 1. **\`.great_cto/lessons.md\`** — project-specific lessons learned
> 2. **\`~/.great_cto/decisions.md\`** — global decisions log (ADR-style, all projects)
> 3. **\`~/.great_cto/verdicts/\`** — past agent verdicts (APPROVED/BLOCKED with rationale)
> 4. Only then read source files for the actual implementation
>
> This prevents re-deriving solved problems and surfaces "we decided this last
> sprint" insights. Agents update these layers via gate approvals (auto) and
> by appending to \`lessons.md\` after retrospectives.

## Goals

- <add your primary goal here>
- <add your second goal here>

## Context

- Tests present: ${detection.hasTests ? "yes" : "no"}
- CI configured: ${detection.hasCI ? "yes" : "no"}
- Detected signals: ${JSON.stringify(detection.signals, null, 2).replace(/\n/g, "\n  ")}

## Notes

Generated from stack auto-detection. The \`archetype\` and \`compliance\`
above are best-effort guesses from your manifest files alone — refine them
when you actually start work:

- For a full audit (gap analysis, tech debt scan, architectural review):
  \`/audit\` in Claude Code.
- For a new feature with vague requirements: \`/start "<description>"\` —
  if your input is sparse the Phase 0 Discovery skill will ask 4–6 questions
  and propose 2–3 concrete approaches (build it / POC first / use a vendor
  instead) before committing to architecture.
- To override the guess directly: edit \`primary:\` and \`compliance:\` in
  this file, then continue.
`;

  writeFileSync(projectMd, content, "utf-8");
  success(`created .great_cto/PROJECT.md ${dim(`(archetype: ${archetype})`)}`);

  // Write ~/.great_cto/guardrails.yml example if it doesn't exist yet.
  // This is the user-level agentshield config — applies across all projects.
  const globalGreatCtoDir = join(homedir(), ".great_cto");
  const guardrailsPath = join(globalGreatCtoDir, "guardrails.yml");
  if (!existsSync(guardrailsPath)) {
    mkdirSync(globalGreatCtoDir, { recursive: true });
    const guardrailsContent = `# ~/.great_cto/guardrails.yml
# User-defined agentshield rules. Loaded and merged with built-in rules on every scan.
# Rules use the same YAML format as agentshield-rules/*.yaml.
#
# action field (user rules only):
#   block  — scan fails (treated as critical finding; blocks gate:ship)
#   audit  — finding reported but scan continues (warning only)
#   redact — same as audit; marks pattern for future content redaction
#
# Example rule — customize with your org's patterns:
#
# - id: UG-001
#   scanner: secrets-in-prompts
#   title: Internal API token pattern
#   severity: critical
#   description: |
#     Detects hardcoded internal API tokens matching the org pattern mytoken_*.
#   remediation: |
#     Move to environment variable. Reference via process.env.MY_TOKEN.
#   patterns:
#     - 'mytoken_[a-z0-9]{32}'
#   action: block
#
# - id: UG-002
#   scanner: prompt-injection
#   title: Audit use of customer data in prompts
#   severity: high
#   description: |
#     Flags when customer PII fields (email, phone, address) are embedded in prompts.
#   remediation: |
#     Replace PII with anonymized tokens before embedding in prompts.
#   patterns:
#     - 'customer\.(email|phone|address|ssn)'
#   action: audit
#   file_globs:
#     - "**/*.ts"
#     - "**/*.py"
#
# Add your own rules below:
`;
    writeFileSync(guardrailsPath, guardrailsContent, "utf-8");
    success(`created ~/.great_cto/guardrails.yml ${dim("(user-level agentshield rules — edit to add org-specific patterns)")}`);
  }

  // Write FLOW.md — compiled delivery flow for agents and user
  const confidence = detectionMeta?.confidence ?? "medium";
  const size = (detection.projectSize ?? "medium") as ProjectSize;
  const flow = compileFlow(archetype, size, detection, compliance, confidence);
  const flowMdPath = join(greatCtoDir, "FLOW.md");
  const generatedAt = new Date().toISOString().slice(0, 10);
  writeFileSync(flowMdPath, renderFlowMd(flow, generatedAt), "utf-8");

  return { projectMdPath: projectMd, created: true, skippedReason: null, flow };
}

/**
 * Slugify a project title into a tenant-id safe for HTTP headers and audit
 * logs. Rules: lowercase, ASCII alnum + dash, collapse, trim, max 48 chars.
 *
 * Examples:
 *   "billing-api"      → "billing-api"
 *   "@acme/web-app"    → "acme-web-app"
 *   "  Foo  Bar 2026"  → "foo-bar-2026"
 */
export function slugifyTenant(title: string): string {
  return title
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48) || "default";
}

function inferProjectTitle(dir: string): string {
  // Prefer package.json name, then directory basename.
  try {
    const pkgPath = join(dir, "package.json");
    if (existsSync(pkgPath)) {
      const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as { name?: string };
      if (pkg.name) return pkg.name;
    }
  } catch { /* ignore */ }
  const parts = dir.split(/[\/\\]/);
  return parts[parts.length - 1] ?? "project";
}
