#!/usr/bin/env bash
# scripts/architect-codebase-map.sh — generate or print .great_cto/CODEBASE.md.
#
# Cache (~30x token reduction on subsequent architect reads) of: entry points,
# module structure (files per directory), god nodes (most-imported modules —
# highest coupling, change carefully), public API surface, routes/endpoints,
# and data models. Only meaningful for non-greenfield projects.
#
# Usage:
#   bash scripts/architect-codebase-map.sh
#   (run only when `greenfield: false` in .great_cto/PROJECT.md)
#
# Behavior:
#   - If .great_cto/CODEBASE.md does not exist: generates it, prints the
#     confirmation line "CODEBASE.md generated → .great_cto/CODEBASE.md".
#   - If it already exists: prints its content (the cache hit path).
#   - Delete .great_cto/CODEBASE.md to force regeneration on next run.

set -uo pipefail

OUT=".great_cto/CODEBASE.md"

if [ ! -f "$OUT" ]; then
  mkdir -p .great_cto
  {
    echo "# Codebase Map"
    echo "> Auto-generated by architect. Refresh: delete and re-run."
    echo ""
    echo "## Entry Points"
    ls main.ts index.ts app.ts server.ts main.py app.py manage.py main.go cmd/main.go \
       src/index.ts src/main.ts src/app.ts 2>/dev/null | head -10
    echo ""
    echo "## Module Structure (files per directory)"
    find . -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.py" -o -name "*.go" \
      -o -name "*.rs" -o -name "*.java" -o -name "*.kt" \) \
      -not -path "*/node_modules/*" -not -path "*/.git/*" \
      -not -path "*/dist/*" -not -path "*/__pycache__/*" \
      | sed 's|/[^/]*$||' | sort | uniq -c | sort -rn | head -20
    echo ""
    echo "## God Nodes (most-imported modules)"
    # TypeScript / JavaScript
    grep -rh "from '" . --include="*.ts" --include="*.tsx" --include="*.js" \
      2>/dev/null | grep -oP "from '[./][^']+'" | sed "s/from '//;s/'//" \
      | sort | uniq -c | sort -rn | head -15
    # Python
    grep -rh "^from \.\|^from \.\." . --include="*.py" 2>/dev/null \
      | awk '{print $2}' | sort | uniq -c | sort -rn | head -10
    # Go
    grep -rh '"\./' . --include="*.go" 2>/dev/null \
      | grep -oP '"[./][^"]*"' | sort | uniq -c | sort -rn | head -10
    echo ""
    echo "## Public API Surface"
    grep -rn "export \(default \)\?function\|export \(default \)\?class\|export const\|export type\|export interface" \
      . --include="*.ts" --include="*.tsx" 2>/dev/null \
      | grep -v "node_modules\|dist\|\.test\." | head -30
    echo ""
    echo "## Routes / Endpoints"
    grep -rn "router\.\|app\.\(get\|post\|put\|delete\|patch\)\|@app\.\|func.*Handler\|@Get\|@Post\|@Put\|@Delete" \
      . --include="*.ts" --include="*.py" --include="*.go" --include="*.java" 2>/dev/null \
      | grep -v "node_modules\|\.test\." | head -25
    echo ""
    echo "## Data Models"
    find . -name "schema.prisma" -o -name "models.py" -o -name "*.sql" \
      -not -path "*/node_modules/*" 2>/dev/null | head -3 | xargs cat 2>/dev/null | head -50
  } > "$OUT" 2>/dev/null
  echo "CODEBASE.md generated → $OUT"
else
  cat "$OUT"
fi
